version: "3"
services:
  worker:
    build:
      context: ./celery_queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: ./celery_queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    container_name: im-postgres
    environment:
        POSTGRES_PASSWORD: postgres
        PGDATA: /opt/pgsql_im/data
    volumes:
        - /datadrive/pgdata:/opt/pgsql/data
    ports:
        - "5433:5432"
